application: enow-staging
version: 1
runtime: go
api_version: go1.8

handlers:
- url: /.*
  script: _go_app
- url: /
  static_files: build/index.html
  upload: /
- url: /swaggerui
  static_files: swaggerui/index.html
  upload: /swaggerui
- url: /swagger.json
  static_files: swagger/swagger.json
  upload: /swagger.json

env_variables:
  TZ: JST

includes:
- env.yaml
